import { config } from 'dotenv';
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { schemes } from './src/db/schema/index.js';

config({ path: '.env.local' });

const connectionString = process.env.DATABASE_URL || process.env.DIRECT_URL;
if (!connectionString) {
  throw new Error('DATABASE_URL or DIRECT_URL must be set');
}

const client = postgres(connectionString);
const db = drizzle(client);

// All these schemes use the Rs 3 Lakh income limit as per NSFDC
const INCOME_LIMIT = '300000';

const scSchemes = [
  {
    slug: 'mcf-micro-credit-finance',
    title: 'Micro Credit Finance (MCF)',
    titleHi: 'माइक्रो क्रेडिट फाइनेंस (एमसीएफ)',
    description: 'Concessional financial assistance for small income-generating activities.',
    descriptionHi: 'छोटी आय-सृजन गतिविधियों के लिए रियायती वित्तीय सहायता।',
    category: 'sc',
    categoryHi: 'अनुसूचित जाति',
    targetGroup: 'Individual entrepreneurs and small businesses',
    targetGroupHi: 'व्यक्तिगत उद्यमी और छोटे व्यवसाय',
    benefits: 'Loan up to 90% of project cost at low interest rates.',
    benefitsHi: 'कम ब्याज दरों पर परियोजना लागत का 90% तक ऋण।',
    eligibility: 'Must belong to Scheduled Caste, annual family income below ₹3.00 Lakhs.',
    eligibilityHi: 'अनुसूचित जाति से संबंधित होना चाहिए, वार्षिक पारिवारिक आय ₹3.00 लाख से कम हो।',
    applicationProcess: 'Apply through State Channelizing Agencies (SCAs).',
    applicationProcessHi: 'राज्य चैनलाइजिंग एजेंसियों (SCA) के माध्यम से आवेदन करें।',
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Aadhaar Card', 'Project Report'],
    officialUrl: 'https://nsfdc.nic.in/',
    ministry: 'Ministry of Social Justice and Empowerment',
    ministryHi: 'सामाजिक न्याय और अधिकारिता मंत्रालय',
    schemeType: 'Loan',
    isActive: true,
    minCost: '0',
    maxCost: '140000',
    incomeLimit: INCOME_LIMIT,
    interestRateMale: '5.00',
    interestRateFemale: '5.00',
    govtFundingPct: '90.00',
    promoterMarginPct: '10.00',
    minMoratorium: 6,
    maxMoratorium: 6,
    maxTenureMonths: 42, // 3.5 years
  },
  {
    slug: 'msy-mahila-samriddhi-yojana',
    title: 'Mahila Samriddhi Yojana (MSY)',
    titleHi: 'महिला समृद्धि योजना (एमएसवाई)',
    description: 'Microfinance scheme specifically for women belonging to the SC category to engage in income-generating activities.',
    descriptionHi: 'विशेष रूप से एससी श्रेणी की महिलाओं को आय-सृजन गतिविधियों में शामिल करने के लिए माइक्रोफाइनेंस योजना।',
    category: 'sc',
    categoryHi: 'अनुसूचित जाति',
    targetGroup: 'Women Entrepreneurs',
    targetGroupHi: 'महिला उद्यमी',
    benefits: 'Concessional loan up to ₹1.40 Lakh with lower interest rate for women.',
    benefitsHi: 'महिलाओं के लिए कम ब्याज दर के साथ ₹1.40 लाख तक का रियायती ऋण।',
    eligibility: 'Must be an SC woman, annual family income below ₹3.00 Lakhs.',
    eligibilityHi: 'एससी महिला होनी चाहिए, वार्षिक पारिवारिक आय ₹3.00 लाख से कम हो।',
    applicationProcess: 'Apply through State Channelizing Agencies (SCAs) or SHGs.',
    applicationProcessHi: 'राज्य चैनलाइजिंग एजेंसियों (SCA) या SHG के माध्यम से आवेदन करें।',
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Aadhaar Card', 'Project Report'],
    officialUrl: 'https://nsfdc.nic.in/',
    ministry: 'Ministry of Social Justice and Empowerment',
    ministryHi: 'सामाजिक न्याय और अधिकारिता मंत्रालय',
    schemeType: 'Loan',
    isActive: true,
    minCost: '0',
    maxCost: '140000',
    incomeLimit: INCOME_LIMIT,
    interestRateMale: null,
    interestRateFemale: '4.00',
    govtFundingPct: '90.00',
    promoterMarginPct: '10.00',
    minMoratorium: 6,
    maxMoratorium: 6,
    maxTenureMonths: 42,
  },
  {
    slug: 'tls-term-loan-scheme',
    title: 'Term Loan Scheme (TLS)',
    titleHi: 'टर्म लोन योजना (टीएलएस)',
    description: 'Primary credit-based scheme for larger projects, supporting self-employment and entrepreneurial ventures.',
    descriptionHi: 'बड़ी परियोजनाओं के लिए प्राथमिक क्रेडिट-आधारित योजना, जो स्वरोजगार और उद्यमशीलता का समर्थन करती है।',
    category: 'sc',
    categoryHi: 'अनुसूचित जाति',
    targetGroup: 'Entrepreneurs',
    targetGroupHi: 'उद्यमी',
    benefits: 'Loan up to ₹50 Lakhs.',
    benefitsHi: '₹50 लाख तक का ऋण।',
    eligibility: 'Must belong to Scheduled Caste, annual family income below ₹3.00 Lakhs.',
    eligibilityHi: 'अनुसूचित जाति से संबंधित होना चाहिए, वार्षिक पारिवारिक आय ₹3.00 लाख से कम हो।',
    applicationProcess: 'Apply through SCAs or designated banks.',
    applicationProcessHi: 'एससीए या नामित बैंकों के माध्यम से आवेदन करें।',
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Aadhaar Card', 'Detailed Project Report (DPR)'],
    officialUrl: 'https://nsfdc.nic.in/',
    ministry: 'Ministry of Social Justice and Empowerment',
    ministryHi: 'सामाजिक न्याय और अधिकारिता मंत्रालय',
    schemeType: 'Loan',
    isActive: true,
    minCost: '140001',
    maxCost: '5000000',
    incomeLimit: INCOME_LIMIT,
    interestRateMale: '6.00',
    interestRateFemale: '6.00',
    govtFundingPct: '90.00',
    promoterMarginPct: '10.00',
    minMoratorium: 6,
    maxMoratorium: 12,
    maxTenureMonths: 120, // 10 years
  },
  {
    slug: 'may-mahila-adhikarita-yojana',
    title: 'Mahila Adhikarita Yojana (MAY)',
    titleHi: 'महिला अधिकारिता योजना (मई)',
    description: 'Financial assistance for SC women in agricultural activities and rural enterprise.',
    descriptionHi: 'कृषि गतिविधियों और ग्रामीण उद्यमों में एससी महिलाओं के लिए वित्तीय सहायता।',
    category: 'sc',
    categoryHi: 'अनुसूचित जाति',
    targetGroup: 'Women in Agriculture/Rural Enterprise',
    targetGroupHi: 'कृषि/ग्रामीण उद्यम में महिलाएं',
    benefits: 'Loan up to ₹2 Lakhs at 5% interest.',
    benefitsHi: '5% ब्याज पर ₹2 लाख तक का ऋण।',
    eligibility: 'SC women, annual family income below ₹3.00 Lakhs.',
    eligibilityHi: 'एससी महिलाएं, वार्षिक पारिवारिक आय ₹3.00 लाख से कम हो।',
    applicationProcess: 'Apply through SCAs.',
    applicationProcessHi: 'SCA के माध्यम से आवेदन करें।',
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Aadhaar Card'],
    officialUrl: 'https://nsfdc.nic.in/',
    ministry: 'Ministry of Social Justice and Empowerment',
    ministryHi: 'सामाजिक न्याय और अधिकारिता मंत्रालय',
    schemeType: 'Loan',
    isActive: true,
    minCost: '0',
    maxCost: '200000',
    incomeLimit: INCOME_LIMIT,
    interestRateMale: null,
    interestRateFemale: '5.00',
    govtFundingPct: '90.00',
    promoterMarginPct: '10.00',
    minMoratorium: 6,
    maxMoratorium: 6,
    maxTenureMonths: 120,
  },
  {
    slug: 'els-dom-education-loan-domestic',
    title: 'Education Loan Scheme (Domestic)',
    titleHi: 'शिक्षा ऋण योजना (घरेलू)',
    description: 'Financial assistance to eligible students for pursuing full-time professional and technical courses in India.',
    descriptionHi: 'भारत में पूर्णकालिक व्यावसायिक और तकनीकी पाठ्यक्रम करने के लिए योग्य छात्रों को वित्तीय सहायता।',
    category: 'sc',
    categoryHi: 'अनुसूचित जाति',
    targetGroup: 'Students',
    targetGroupHi: 'छात्र',
    benefits: 'Education loan up to ₹10 Lakhs.',
    benefitsHi: '₹10 लाख तक का शिक्षा ऋण।',
    eligibility: 'SC student securing admission in recognized professional/technical courses, family income below ₹3.00 Lakhs.',
    eligibilityHi: 'मान्यता प्राप्त व्यावसायिक/तकनीकी पाठ्यक्रमों में प्रवेश पाने वाले एससी छात्र, पारिवारिक आय ₹3.00 लाख से कम।',
    applicationProcess: 'Apply through SCAs or banks.',
    applicationProcessHi: 'SCA या बैंकों के माध्यम से आवेदन करें।',
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Admission Letter', 'Fee Structure'],
    officialUrl: 'https://nsfdc.nic.in/',
    ministry: 'Ministry of Social Justice and Empowerment',
    ministryHi: 'सामाजिक न्याय और अधिकारिता मंत्रालय',
    schemeType: 'Education Loan',
    isActive: true,
    minCost: '0',
    maxCost: '1000000',
    incomeLimit: INCOME_LIMIT,
    interestRateMale: '4.00',
    interestRateFemale: '3.50',
    govtFundingPct: '90.00',
    promoterMarginPct: '0.00',
    minMoratorium: 6,
    maxMoratorium: 12,
    maxTenureMonths: 180, // 15 years
  },
  {
    slug: 'els-abr-education-loan-abroad',
    title: 'Education Loan Scheme (Abroad)',
    titleHi: 'शिक्षा ऋण योजना (विदेश)',
    description: 'Financial assistance to eligible students for pursuing full-time professional and technical courses abroad.',
    descriptionHi: 'विदेश में पूर्णकालिक व्यावसायिक और तकनीकी पाठ्यक्रम करने के लिए योग्य छात्रों को वित्तीय सहायता।',
    category: 'sc',
    categoryHi: 'अनुसूचित जाति',
    targetGroup: 'Students',
    targetGroupHi: 'छात्र',
    benefits: 'Education loan up to ₹20 Lakhs.',
    benefitsHi: '₹20 लाख तक का शिक्षा ऋण।',
    eligibility: 'SC student securing admission abroad, family income below ₹3.00 Lakhs.',
    eligibilityHi: 'विदेश में प्रवेश पाने वाले एससी छात्र, पारिवारिक आय ₹3.00 लाख से कम।',
    applicationProcess: 'Apply through SCAs or banks.',
    applicationProcessHi: 'SCA या बैंकों के माध्यम से आवेदन करें।',
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Admission Letter', 'Fee Structure', 'Visa details'],
    officialUrl: 'https://nsfdc.nic.in/',
    ministry: 'Ministry of Social Justice and Empowerment',
    ministryHi: 'सामाजिक न्याय और अधिकारिता मंत्रालय',
    schemeType: 'Education Loan',
    isActive: true,
    minCost: '0',
    maxCost: '2000000',
    incomeLimit: INCOME_LIMIT,
    interestRateMale: '4.00',
    interestRateFemale: '3.50',
    govtFundingPct: '90.00',
    promoterMarginPct: '0.00',
    minMoratorium: 6,
    maxMoratorium: 12,
    maxTenureMonths: 180,
  },
  {
    slug: 'gbs-green-business-scheme',
    title: 'Green Business Scheme (GBS)',
    titleHi: 'हरित व्यापार योजना (जीबीएस)',
    description: 'Financial support for eco-friendly and climate-conscious activities that generate income.',
    descriptionHi: 'आय उत्पन्न करने वाली पर्यावरण-अनुकूल गतिविधियों के लिए वित्तीय सहायता।',
    category: 'sc',
    categoryHi: 'अनुसूचित जाति',
    targetGroup: 'Entrepreneurs in Green Business',
    targetGroupHi: 'हरित व्यापार में उद्यमी',
    benefits: 'Loan up to ₹30 Lakhs for eco-friendly businesses.',
    benefitsHi: 'पर्यावरण-अनुकूल व्यवसायों के लिए ₹30 लाख तक का ऋण।',
    eligibility: 'SC category, family income below ₹3.00 Lakhs.',
    eligibilityHi: 'एससी श्रेणी, पारिवारिक आय ₹3.00 लाख से कम।',
    applicationProcess: 'Apply through SCAs.',
    applicationProcessHi: 'SCA के माध्यम से आवेदन करें।',
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Aadhaar Card', 'Project Report'],
    officialUrl: 'https://nsfdc.nic.in/',
    ministry: 'Ministry of Social Justice and Empowerment',
    ministryHi: 'सामाजिक न्याय और अधिकारिता मंत्रालय',
    schemeType: 'Loan',
    isActive: true,
    minCost: '0',
    maxCost: '3000000',
    incomeLimit: INCOME_LIMIT,
    interestRateMale: '4.00',
    interestRateFemale: '3.00',
    govtFundingPct: '90.00',
    promoterMarginPct: '10.00',
    minMoratorium: 6,
    maxMoratorium: 12,
    maxTenureMonths: 120,
  },
  {
    slug: 'suy-swachhta-udyami-yojana',
    title: 'Swachhta Udyami Yojana (SUY)',
    titleHi: 'स्वच्छता उद्यमी योजना (एसयूवाई)',
    description: 'Focused on cleanliness and providing sustainable livelihoods to Safai Karamcharis and manual scavengers.',
    descriptionHi: 'स्वच्छता और सफाई कर्मचारियों को स्थायी आजीविका प्रदान करने पर केंद्रित।',
    category: 'sc',
    categoryHi: 'अनुसूचित जाति',
    targetGroup: 'Safai Karamcharis and Manual Scavengers',
    targetGroupHi: 'सफाई कर्मचारी',
    benefits: 'Loan up to ₹50 Lakhs for sanitation-related vehicles or pay-and-use toilets.',
    benefitsHi: 'स्वच्छता संबंधी वाहनों या शौचालयों के लिए ₹50 लाख तक का ऋण।',
    eligibility: 'Safai Karamcharis / Manual Scavengers. No income limit.',
    eligibilityHi: 'सफाई कर्मचारी। कोई आय सीमा नहीं।',
    applicationProcess: 'Apply through SCAs or NSKFDC.',
    applicationProcessHi: 'SCA या NSKFDC के माध्यम से आवेदन करें।',
    requiredDocuments: ['Occupation Certificate', 'Aadhaar Card', 'Project Report'],
    officialUrl: 'https://nsfdc.nic.in/',
    ministry: 'Ministry of Social Justice and Empowerment',
    ministryHi: 'सामाजिक न्याय और अधिकारिता मंत्रालय',
    schemeType: 'Loan',
    isActive: true,
    minCost: '0',
    maxCost: '5000000',
    incomeLimit: '999999999', // No practical limit
    interestRateMale: '4.00',
    interestRateFemale: '4.00',
    govtFundingPct: '90.00',
    promoterMarginPct: '10.00',
    minMoratorium: 6,
    maxMoratorium: 6,
    maxTenureMonths: 120,
  }
];

async function seed() {
  console.log(`Starting to seed ${scSchemes.length} SC schemes...`);
  try {
    for (const scheme of scSchemes) {
      // @ts-ignore
      await db.insert(schemes)
        .values(scheme)
        .onConflictDoUpdate({
          target: schemes.slug,
          set: scheme,
        });
      console.log(`Upserted scheme: ${scheme.slug}`);
    }
    console.log('Seeding SC Schemes complete!');
  } catch (error) {
    console.error('Error seeding schemes:', error);
  } finally {
    await client.end();
  }
}

seed();
