"use server";

import { db } from "@/db";
import { 
  loanDossiers, 
  schemes, 
  channelPartners, 
  partnerHealthMetrics 
} from "@/db/schema";
import { getAuthUser, getProfile } from "@/lib/auth-cache";
import { eq, and } from "drizzle-orm";
import { createHash } from "crypto";
import { calculateRepaymentSchedule } from "@/features/repayment/emi-engine";
import { findBestBranchForProfile } from "@/features/routing/routing-service";

export async function generateDossier(
  schemeId: string, 
  ifsc: string, 
  projectCost: number, 
  moratorium: number
) {
  try {
    const user = await getAuthUser();
    if (!user) {
      return { success: false, error: "Unauthorized" };
    }

    const profile = await getProfile();
    if (!profile) {
      return { success: false, error: "Profile not found" };
    }

    // 1. Fetch the scheme to validate and get financial policy
    const schemeList = await db
      .select()
      .from(schemes)
      .where(and(eq(schemes.id, schemeId), eq(schemes.isActive, true)))
      .limit(1);

    const scheme = schemeList[0];
    if (!scheme) {
      return { success: false, error: "Scheme is inactive or not found." };
    }

    // 2. Fetch the branch to validate routing gatekeeper rules
    const branchList = await db
      .select({
        ifsc: channelPartners.ifsc,
        isActive: channelPartners.isActive,
        isFrozen: partnerHealthMetrics.isFrozen,
        allocatedQuota: partnerHealthMetrics.allocatedQuota,
        disbursedQuota: partnerHealthMetrics.disbursedQuota,
        npaRatio: partnerHealthMetrics.npaRatio
      })
      .from(channelPartners)
      .leftJoin(partnerHealthMetrics, eq(channelPartners.ifsc, partnerHealthMetrics.ifsc))
      .where(eq(channelPartners.ifsc, ifsc))
      .limit(1);

    const branch = branchList[0];
    if (!branch) {
      return { success: false, error: "Branch not found." };
    }

    if (!branch.isActive) {
      return { success: false, error: "Branch is currently inactive." };
    }

    if (branch.isFrozen) {
      return { success: false, error: "Branch operations are currently frozen." };
    }

    const allocated = Number(branch.allocatedQuota || 0);
    const disbursed = Number(branch.disbursedQuota || 0);
    const npa = Number(branch.npaRatio || 0);

    if (allocated - disbursed <= 0) {
      return { success: false, error: "Branch has exhausted its funding quota." };
    }

    if (npa > 0.1500) {
      return { success: false, error: "Branch NPA ratio exceeds 15% threshold." };
    }

    // 3. Re-calculate EMI on the server
    const schedule = calculateRepaymentSchedule(
      {
        projectCost,
        gender: profile.gender || null,
        selectedMoratoriumMonths: moratorium,
      },
      {
        govtFundingPct: Number(scheme.govtFundingPct) || 90,
        promoterMarginPct: Number(scheme.promoterMarginPct) || 10,
        interestRateMale: scheme.interestRateMale ? Number(scheme.interestRateMale) : null,
        interestRateFemale: scheme.interestRateFemale ? Number(scheme.interestRateFemale) : null,
        minMoratorium: scheme.minMoratorium || 6,
        maxMoratorium: scheme.maxMoratorium || 6,
        maxTenureMonths: scheme.maxTenureMonths || 42,
      }
    );

    const calculatedEmi = schedule.phase2.emi;

    // 4. Generate Phone Hash & Tracking Code
    // If we have a phone on the auth user use it, otherwise use userId as seed to ensure privacy
    const rawPhone = user.phone || profile.userId; 
    const phoneHash = createHash("sha256").update(rawPhone).digest("hex");

    const datePrefix = new Date().toISOString().slice(0, 7).replace("-", ""); // YYYYMM
    const randomHex = Math.random().toString(16).substring(2, 8).toUpperCase();
    const trackingCode = `CRX-${datePrefix}-${randomHex}`;

    // 5. Insert into Database
    await db.insert(loanDossiers).values({
      trackingCode,
      userId: profile.userId,
      applicantName: profile.fullName,
      phoneHash,
      annualIncome: profile.annualIncome ? String(profile.annualIncome) : "0",
      projectCost: String(projectCost),
      calculatedEmi: String(calculatedEmi),
      eligibleSchemeId: scheme.id,
      allocatedPartnerIfsc: ifsc,
      selectedMoratorium: moratorium,
      status: 'DOSSIER_GENERATED'
    });

    return { success: true, trackingCode };
  } catch (error: any) {
    console.error("Failed to generate dossier:", error);
    return { success: false, error: "An unexpected error occurred while generating the dossier." };
  }
}

export async function autoGenerateDossier(
  schemeId: string, 
  projectCost: number, 
  moratorium: number
) {
  try {
    const user = await getAuthUser();
    if (!user) {
      return { success: false, error: "Unauthorized" };
    }

    const profile = await getProfile();
    if (!profile) {
      return { success: false, error: "Profile not found" };
    }

    if (!profile.state) {
      return { success: false, error: "State is required in your profile to auto-allocate a branch." };
    }

    const bestBranch = await findBestBranchForProfile(profile.state, profile.district || undefined);
    
    if (!bestBranch) {
      return { success: false, error: "No viable partner branches found in your state/district." };
    }

    return await generateDossier(schemeId, bestBranch.ifsc, projectCost, moratorium);
  } catch (error: any) {
    console.error("Failed to auto-generate dossier:", error);
    return { success: false, error: "An unexpected error occurred during automatic branch allocation." };
  }
}
