import { config } from 'dotenv'
import { drizzle } from 'drizzle-orm/postgres-js'
import postgres from 'postgres'
import { schemes } from './schema'

config({ path: '.env.local' })

if (!process.env.DATABASE_URL) {
  throw new Error('DATABASE_URL is not set')
}

const connectionString = process.env.DATABASE_URL
const client = postgres(connectionString)
const db = drizzle(client)

const SEED_SCHEMES = [
  {
    slug: 'kisan-samman-nidhi',
    title: 'Kisan Samman Nidhi',
    titleHi: 'किसान सम्मान निधि',
    description: 'Income support to all landholding farmers families in the country.',
    descriptionHi: 'देश में सभी भूमिधारी किसान परिवारों को आय सहायता।',
    category: 'Agriculture',
    categoryHi: 'कृषि',
    targetGroup: 'Farmers',
    targetGroupHi: 'किसान',
    benefits: 'Rs. 6000 per year in three equal installments.',
    benefitsHi: 'तीन समान किस्तों में प्रति वर्ष 6000 रुपये।',
    eligibility: 'All landholding farmers families, having cultivable land in their names.',
    eligibilityHi: 'सभी भूमिधारी किसान परिवार, जिनके नाम पर खेती योग्य भूमि है।',
    applicationProcess: 'Apply online on pmkisan.gov.in or via CSC.',
    applicationProcessHi: 'pmkisan.gov.in पर या CSC के माध्यम से ऑनलाइन आवेदन करें।',
    requiredDocuments: ['Aadhaar Card', 'Bank Account Details', 'Land Holding Documents'],
    officialUrl: 'https://pmkisan.gov.in',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    ministryHi: 'कृषि और किसान कल्याण मंत्रालय',
    schemeType: 'Central Sector Scheme',
    occupationTags: ['farmer', 'agriculture'],
    stateTags: [],
    genderTags: [],
    educationTags: [],
    ageMin: 18,
    ageMax: null,
    incomeLimit: null,
    isActive: true,
  },
  {
    slug: 'national-scholarship-scheme',
    title: 'National Means cum Merit Scholarship',
    titleHi: 'राष्ट्रीय साधन सह योग्यता छात्रवृत्ति',
    description: 'Scholarships for meritorious students of economically weaker sections.',
    descriptionHi: 'आर्थिक रूप से कमजोर वर्गों के मेधावी छात्रों के लिए छात्रवृत्ति।',
    category: 'Education',
    categoryHi: 'शिक्षा',
    targetGroup: 'Students',
    targetGroupHi: 'छात्र',
    benefits: 'Rs. 12000 per annum (Rs. 1000 per month).',
    benefitsHi: '12000 रुपये प्रति वर्ष (1000 रुपये प्रति माह)।',
    eligibility: 'Students studying in Class IX. Parental income should not exceed Rs. 3,50,000 per annum.',
    eligibilityHi: 'नौवीं कक्षा में पढ़ने वाले छात्र। माता-पिता की आय 3,50,000 रुपये प्रति वर्ष से अधिक नहीं होनी चाहिए।',
    applicationProcess: 'Apply through National Scholarship Portal.',
    applicationProcessHi: 'राष्ट्रीय छात्रवृत्ति पोर्टल के माध्यम से आवेदन करें।',
    requiredDocuments: ['Income Certificate', 'Aadhaar Card', 'School ID', 'Bank Account Details'],
    officialUrl: 'https://scholarships.gov.in',
    ministry: 'Ministry of Education',
    ministryHi: 'शिक्षा मंत्रालय',
    schemeType: 'Centrally Sponsored Scheme',
    occupationTags: ['student'],
    stateTags: [],
    genderTags: [],
    educationTags: [],
    ageMin: 13,
    ageMax: 16,
    incomeLimit: '350000',
    isActive: true,
  },
  {
    slug: 'doctor-rural-incentive-mp',
    title: 'Doctor Rural Incentive Scheme (MP)',
    titleHi: 'डॉक्टर ग्रामीण प्रोत्साहन योजना (एमपी)',
    description: 'Incentive for medical professionals to serve in rural areas of Madhya Pradesh.',
    descriptionHi: 'मध्य प्रदेश के ग्रामीण क्षेत्रों में सेवा करने के लिए चिकित्सा पेशेवरों को प्रोत्साहन।',
    category: 'Healthcare',
    categoryHi: 'स्वास्थ्य देखभाल',
    targetGroup: 'Medical Professionals',
    targetGroupHi: 'चिकित्सा पेशेवर',
    benefits: 'Additional 20% to 30% of basic salary as incentive.',
    benefitsHi: 'प्रोत्साहन के रूप में मूल वेतन का अतिरिक्त 20% से 30%।',
    eligibility: 'Must be a registered medical practitioner working in designated rural or tribal health centers in MP.',
    eligibilityHi: 'एमपी में नामित ग्रामीण या आदिवासी स्वास्थ्य केंद्रों में काम करने वाला पंजीकृत चिकित्सक होना चाहिए।',
    applicationProcess: 'Submit joining report at the respective CMHO office.',
    applicationProcessHi: 'संबंधित सीएमएचओ कार्यालय में ज्वाइनिंग रिपोर्ट जमा करें।',
    requiredDocuments: ['Medical Registration Certificate', 'Posting Order', 'Bank Account Details'],
    officialUrl: 'https://health.mp.gov.in',
    ministry: 'Department of Public Health and Family Welfare (MP)',
    ministryHi: 'लोक स्वास्थ्य एवं परिवार कल्याण विभाग (म.प्र.)',
    schemeType: 'State Scheme',
    occupationTags: ['doctor', 'medical', 'nurse', 'healthcare'],
    stateTags: ['madhya_pradesh'],
    genderTags: [],
    educationTags: ['bachelor', 'master'],
    ageMin: 22,
    ageMax: 60,
    incomeLimit: null,
    isActive: true,
  },
  {
    slug: 'mukhyamantri-kanya-vivah-yojana',
    title: 'Mukhyamantri Kanya Vivah Yojana',
    titleHi: 'मुख्यमंत्री कन्या विवाह योजना',
    description: 'Financial assistance for the marriage of girls from poor families.',
    descriptionHi: 'गरीब परिवारों की लड़कियों की शादी के लिए वित्तीय सहायता।',
    category: 'Social Welfare',
    categoryHi: 'समाज कल्याण',
    targetGroup: 'Women from poor families',
    targetGroupHi: 'गरीब परिवारों की महिलाएं',
    benefits: 'Financial assistance of Rs. 51,000 for marriage.',
    benefitsHi: 'विवाह के लिए 51,000 रुपये की वित्तीय सहायता।',
    eligibility: 'The girl must be 18 years or above. The family must be domiciled in Madhya Pradesh and living below the poverty line.',
    eligibilityHi: 'लड़की की उम्र 18 साल या उससे अधिक होनी चाहिए। परिवार मध्य प्रदेश का निवासी होना चाहिए और गरीबी रेखा से नीचे जीवन यापन करना चाहिए।',
    applicationProcess: 'Apply at Gram Panchayat / Janpad Panchayat or Urban Local Body.',
    applicationProcessHi: 'ग्राम पंचायत / जनपद पंचायत या शहरी स्थानीय निकाय में आवेदन करें।',
    requiredDocuments: ['Age Proof', 'BPL Card', 'Domicile Certificate', 'Bank Account Details'],
    officialUrl: 'http://samagra.gov.in',
    ministry: 'Department of Social Justice and Disabled Person Welfare',
    ministryHi: 'सामाजिक न्याय एवं निशक्तजन कल्याण विभाग',
    schemeType: 'State Scheme',
    occupationTags: [],
    stateTags: ['madhya_pradesh'],
    genderTags: ['female'],
    educationTags: [],
    ageMin: 18,
    ageMax: null,
    incomeLimit: '100000',
    isActive: true,
  },
  {
    slug: 'pm-mudra-yojana',
    title: 'Pradhan Mantri Mudra Yojana (PMMY)',
    titleHi: 'प्रधानमंत्री मुद्रा योजना (PMMY)',
    description: 'Provides loans up to 10 lakh to the non-corporate, non-farm small/micro enterprises.',
    descriptionHi: 'गैर-कॉर्पोरेट, गैर-कृषि छोटे/सूक्ष्म उद्यमों को 10 लाख तक का ऋण प्रदान करता है।',
    category: 'Business & Entrepreneurship',
    categoryHi: 'व्यापार और उद्यमिता',
    targetGroup: 'Small business owners, Entrepreneurs',
    targetGroupHi: 'छोटे व्यवसाय के मालिक, उद्यमी',
    benefits: 'Collateral free loans classified into Shishu (upto 50,000), Kishore (50,000 to 5 Lakh) and Tarun (5 Lakh to 10 Lakh).',
    benefitsHi: 'शिशु (50,000 तक), किशोर (50,000 से 5 लाख) और तरुण (5 लाख से 10 लाख) में वर्गीकृत संपार्श्विक मुक्त ऋण।',
    eligibility: 'Any Indian Citizen who has a business plan for a non-farm sector income generating activity.',
    eligibilityHi: 'कोई भी भारतीय नागरिक जिसके पास गैर-कृषि क्षेत्र आय सृजन गतिविधि के लिए व्यवसाय योजना है।',
    applicationProcess: 'Apply at any bank, NBFC, MFI or online at Udyamimitra portal.',
    applicationProcessHi: 'किसी भी बैंक, एनबीएफसी, एमएफआई या उद्यमीमित्र पोर्टल पर ऑनलाइन आवेदन करें।',
    requiredDocuments: ['Identity Proof', 'Address Proof', 'Business Proof', 'Project Report'],
    officialUrl: 'https://www.mudra.org.in',
    ministry: 'Ministry of Finance',
    ministryHi: 'वित्त मंत्रालय',
    schemeType: 'Central Sector Scheme',
    occupationTags: ['business', 'entrepreneur', 'self_employed'],
    stateTags: [],
    genderTags: [],
    educationTags: [],
    ageMin: 18,
    ageMax: 65,
    incomeLimit: null,
    isActive: true,
  },
  {
    slug: 'ladli-laxmi-yojana',
    title: 'Ladli Laxmi Yojana',
    titleHi: 'लाड़ली लक्ष्मी योजना',
    description: 'Welfare scheme by the Government of Madhya Pradesh to improve the educational, health, and economic status of girl children.',
    descriptionHi: 'बालिकाओं की शैक्षिक, स्वास्थ्य और आर्थिक स्थिति में सुधार के लिए मध्य प्रदेश सरकार की कल्याणकारी योजना।',
    category: 'Education & Welfare',
    categoryHi: 'शिक्षा एवं कल्याण',
    targetGroup: 'Girl children and their families',
    targetGroupHi: 'बालिकाएं और उनके परिवार',
    benefits: 'Total of ₹1.18 lakh financial assistance at various stages of the girl\'s life to support her education and discourage child marriage.',
    benefitsHi: 'बालिका की शिक्षा का समर्थन करने और बाल विवाह को हतोत्साहित करने के लिए उसके जीवन के विभिन्न चरणों में कुल ₹1.18 लाख की वित्तीय सहायता।',
    eligibility: 'Girls born on or after Jan 1, 2006. Parents must be residents of MP, non-income tax payers, with max two children.',
    eligibilityHi: '1 जनवरी 2006 को या उसके बाद जन्मी लड़कियाँ। माता-पिता एमपी के निवासी होने चाहिए, आयकर दाता नहीं होने चाहिए, और अधिकतम दो बच्चे होने चाहिए।',
    applicationProcess: 'Apply directly through Anganwadi worker or online portal.',
    applicationProcessHi: 'आंगनवाड़ी कार्यकर्ता या ऑनलाइन पोर्टल के माध्यम से सीधे आवेदन करें।',
    requiredDocuments: ['Birth Certificate', 'Aadhaar Card', 'Samagra ID', 'Bank Account Details', 'Photo'],
    officialUrl: 'http://ladlilaxmi.mp.gov.in/',
    ministry: 'Women and Child Development Department (MP)',
    ministryHi: 'महिला एवं बाल विकास विभाग (म.प्र.)',
    schemeType: 'State Scheme',
    occupationTags: [],
    stateTags: ['madhya_pradesh'],
    genderTags: ['female'],
    educationTags: [],
    ageMin: 0,
    ageMax: 21,
    incomeLimit: '250000',
    isActive: true,
  },
  {
    slug: 'ladli-behna-yojana',
    title: 'Mukhyamantri Ladli Behna Yojana',
    titleHi: 'मुख्यमंत्री लाड़ली बहना योजना',
    description: 'Initiative by Madhya Pradesh Government to empower women economically, improve health, and enhance decision-making.',
    descriptionHi: 'महिलाओं को आर्थिक रूप से सशक्त बनाने, स्वास्थ्य में सुधार और निर्णय लेने की क्षमता बढ़ाने के लिए मध्य प्रदेश सरकार की पहल।',
    category: 'Social Welfare',
    categoryHi: 'समाज कल्याण',
    targetGroup: 'Married women (including widows, divorced)',
    targetGroupHi: 'विवाहित महिलाएं (विधवाओं, तलाकशुदा सहित)',
    benefits: 'Monthly financial aid of ₹1,250 (₹15,000 annually) transferred via DBT.',
    benefitsHi: '₹1,250 की मासिक वित्तीय सहायता (₹15,000 सालाना) DBT के माध्यम से हस्तांतरित की जाती है।',
    eligibility: 'Married women aged 21 to 60 years. Permanent residents of MP. Combined family income less than ₹2.5 lakh. Non-income tax payers.',
    eligibilityHi: '21 से 60 वर्ष आयु की विवाहित महिलाएं। एमपी की स्थायी निवासी। परिवार की संयुक्त आय ₹2.5 लाख से कम। आयकर दाता नहीं होनी चाहिए।',
    applicationProcess: 'Apply online on official portal or at designated Gram Panchayat / Ward offices.',
    applicationProcessHi: 'आधिकारिक पोर्टल पर या नामित ग्राम पंचायत/वार्ड कार्यालयों में ऑनलाइन आवेदन करें।',
    requiredDocuments: ['Aadhaar Card', 'Samagra ID', 'Bank Passbook (Aadhaar linked)', 'Residency Proof'],
    officialUrl: 'https://cmladlibahna.mp.gov.in',
    ministry: 'Women and Child Development Department (MP)',
    ministryHi: 'महिला एवं बाल विकास विभाग (म.प्र.)',
    schemeType: 'State Scheme',
    occupationTags: [],
    stateTags: ['madhya_pradesh'],
    genderTags: ['female'],
    educationTags: [],
    ageMin: 21,
    ageMax: 60,
    incomeLimit: '250000',
    isActive: true,
  },
  {
    slug: 'sukanya-samriddhi-yojana',
    title: 'Sukanya Samriddhi Yojana',
    titleHi: 'सुकन्या समृद्धि योजना',
    description: 'A government-backed savings scheme targeted at the parents of girl children, offering high interest rates and tax benefits.',
    descriptionHi: 'बालिकाओं के माता-पिता को लक्षित सरकार समर्थित बचत योजना, जो उच्च ब्याज दर और कर लाभ प्रदान करती है।',
    category: 'Education & Welfare',
    categoryHi: 'शिक्षा एवं कल्याण',
    targetGroup: 'Girl children',
    targetGroupHi: 'बालिकाएं',
    benefits: 'High interest rate, tax deductions under Section 80C, and financial security for the girl child\'s future education and marriage.',
    benefitsHi: 'उच्च ब्याज दर, धारा 80C के तहत कर कटौती, और बालिका की भविष्य की शिक्षा और विवाह के लिए वित्तीय सुरक्षा।',
    eligibility: 'Parents or legal guardians of a girl child. The account must be opened before the girl reaches 10 years of age. Maximum 2 accounts per family.',
    eligibilityHi: 'बालिका के माता-पिता या कानूनी अभिभावक। लड़की के 10 वर्ष की आयु तक पहुंचने से पहले खाता खोला जाना चाहिए। प्रति परिवार अधिकतम 2 खाते।',
    applicationProcess: 'Open an account at any post office or authorized commercial bank branches.',
    applicationProcessHi: 'किसी भी डाकघर या अधिकृत वाणिज्यिक बैंक शाखाओं में खाता खोलें।',
    requiredDocuments: ['Birth Certificate of Girl Child', 'Identity Proof of Parent', 'Address Proof of Parent'],
    officialUrl: 'https://www.nsiindia.gov.in',
    ministry: 'Ministry of Finance',
    ministryHi: 'वित्त मंत्रालय',
    schemeType: 'Central Sector Scheme',
    occupationTags: [],
    stateTags: [],
    genderTags: ['female'],
    educationTags: [],
    ageMin: 0,
    ageMax: 10,
    incomeLimit: null,
    isActive: true,
  },
  {
    slug: 'ayushman-bharat-pm-jay',
    title: 'Ayushman Bharat PM-JAY',
    titleHi: 'आयुष्मान भारत पीएम-जय',
    description: 'The world\'s largest health insurance/ assurance scheme fully financed by the government, providing a cover of Rs. 5 lakhs per family per year for secondary and tertiary care hospitalization.',
    descriptionHi: 'पूरी तरह से सरकार द्वारा वित्तपोषित दुनिया की सबसे बड़ी स्वास्थ्य बीमा योजना, जो माध्यमिक और तृतीयक देखभाल अस्पताल में भर्ती होने के लिए प्रति परिवार प्रति वर्ष 5 लाख रुपये का कवर प्रदान करती है।',
    category: 'Healthcare',
    categoryHi: 'स्वास्थ्य देखभाल',
    targetGroup: 'Poor and vulnerable families (BPL)',
    targetGroupHi: 'गरीब और कमजोर परिवार (बीपीएल)',
    benefits: 'Health cover of Rs. 5 lakhs per family per year for secondary and tertiary care hospitalization across public and private empaneled hospitals in India.',
    benefitsHi: 'भारत में सार्वजनिक और निजी पैनलबद्ध अस्पतालों में माध्यमिक और तृतीयक देखभाल के लिए प्रति परिवार प्रति वर्ष 5 लाख रुपये का स्वास्थ्य कवर।',
    eligibility: 'Based on the deprivation and occupational criteria of the Socio-Economic Caste Census (SECC) 2011.',
    eligibilityHi: 'सामाजिक-आर्थिक जाति जनगणना (SECC) 2011 के अभाव और व्यावसायिक मानदंडों के आधार पर।',
    applicationProcess: 'Verify eligibility at PMJAY portal or hospital, generate Golden Card using Aadhaar and Ration Card.',
    applicationProcessHi: 'पीएमजय पोर्टल या अस्पताल में पात्रता सत्यापित करें, आधार और राशन कार्ड का उपयोग करके गोल्डन कार्ड जनरेट करें।',
    requiredDocuments: ['Aadhaar Card', 'Ration Card', 'Mobile Number'],
    officialUrl: 'https://pmjay.gov.in',
    ministry: 'Ministry of Health and Family Welfare',
    ministryHi: 'स्वास्थ्य और परिवार कल्याण मंत्रालय',
    schemeType: 'Centrally Sponsored Scheme',
    occupationTags: [],
    stateTags: [],
    genderTags: [],
    educationTags: [],
    ageMin: null,
    ageMax: null,
    incomeLimit: '100000',
    isActive: true,
  },
  {
    slug: 'post-matric-scholarship-sc-st',
    title: 'Post Matric Scholarship for SC/ST',
    titleHi: 'अनुसूचित जाति/जनजाति के लिए पोस्ट मैट्रिक छात्रवृत्ति',
    description: 'Financial assistance to Scheduled Caste/Scheduled Tribe students studying at post matriculation or post-secondary stage to enable them to complete their education.',
    descriptionHi: 'अनुसूचित जाति/अनुसूचित जनजाति के छात्रों को पोस्ट मैट्रिक या उत्तर-माध्यमिक स्तर पर अध्ययन के लिए वित्तीय सहायता।',
    category: 'Education',
    categoryHi: 'शिक्षा',
    targetGroup: 'SC/ST Students',
    targetGroupHi: 'एससी/एसटी छात्र',
    benefits: 'Covers maintenance allowance, reimbursement of compulsory non-refundable fees, study tour charges, and thesis typing/printing charges.',
    benefitsHi: 'अनुरक्षण भत्ता, अनिवार्य गैर-वापसी योग्य शुल्क की प्रतिपूर्ति, अध्ययन दौरे के शुल्क को कवर करता है।',
    eligibility: 'Students belonging to SC/ST categories studying in recognized post-matriculation courses. Parental income should not exceed Rs. 2.5 lakhs per annum.',
    eligibilityHi: 'मान्यता प्राप्त पोस्ट-मैट्रिक पाठ्यक्रमों में पढ़ने वाले एससी/एसटी श्रेणियों के छात्र। माता-पिता की आय 2.5 लाख रुपये प्रति वर्ष से अधिक नहीं होनी चाहिए।',
    applicationProcess: 'Apply online via the National Scholarship Portal (NSP) or respective state portals.',
    applicationProcessHi: 'राष्ट्रीय छात्रवृत्ति पोर्टल (एनएसपी) या संबंधित राज्य पोर्टलों के माध्यम से ऑनलाइन आवेदन करें।',
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Aadhaar Card', 'Bank Account Details', 'Fee Receipt', 'Previous Year Marksheet'],
    officialUrl: 'https://scholarships.gov.in',
    ministry: 'Ministry of Social Justice and Empowerment / Tribal Affairs',
    ministryHi: 'सामाजिक न्याय और अधिकारिता मंत्रालय / जनजातीय मामले',
    schemeType: 'Centrally Sponsored Scheme',
    occupationTags: ['student'],
    stateTags: [],
    genderTags: [],
    educationTags: [],
    ageMin: 15,
    ageMax: null,
    incomeLimit: '250000',
    isActive: true,
  },
  {
    slug: 'mukhya-mantri-yuva-swarozgar-yojana-up',
    title: 'Mukhya Mantri Yuva Swarozgar Yojana (UP)',
    titleHi: 'मुख्यमंत्री युवा स्वरोजगार योजना (यूपी)',
    description: 'Provides financial assistance to the educated unemployed youth of Uttar Pradesh to start their own enterprise/industry.',
    descriptionHi: 'उत्तर प्रदेश के शिक्षित बेरोजगार युवाओं को अपना उद्यम/उद्योग शुरू करने के लिए वित्तीय सहायता प्रदान करता है।',
    category: 'Business & Entrepreneurship',
    categoryHi: 'व्यापार और उद्यमिता',
    targetGroup: 'Unemployed Youth in UP',
    targetGroupHi: 'यूपी में बेरोजगार युवा',
    benefits: 'Margin money subsidy up to 25% of the project cost. Max loan for industry is Rs. 25 Lakhs, and for service sector is Rs. 10 Lakhs.',
    benefitsHi: 'परियोजना लागत के 25% तक मार्जिन मनी सब्सिडी। उद्योग के लिए अधिकतम ऋण 25 लाख रुपये है।',
    eligibility: 'Age between 18 to 40 years. Minimum education: High School pass. Must be a resident of Uttar Pradesh and not a defaulter in any bank.',
    eligibilityHi: 'आयु 18 से 40 वर्ष के बीच। न्यूनतम शिक्षा: हाई स्कूल पास। उत्तर प्रदेश का निवासी होना चाहिए।',
    applicationProcess: 'Apply online through the Diwan-e-Swarozgar portal.',
    applicationProcessHi: 'दीवान-ए-स्वरोजगार पोर्टल के माध्यम से ऑनलाइन आवेदन करें।',
    requiredDocuments: ['Aadhaar Card', 'Age Proof', 'Educational Certificate', 'Domicile Certificate (UP)', 'Project Report'],
    officialUrl: 'https://diupmsme.upsdc.gov.in',
    ministry: 'Department of MSME and Export Promotion (UP)',
    ministryHi: 'एमएसएमई और निर्यात संवर्धन विभाग (यूपी)',
    schemeType: 'State Scheme',
    occupationTags: ['student', 'unemployed', 'business', 'entrepreneur'],
    stateTags: ['uttar_pradesh'],
    genderTags: [],
    educationTags: ['high_school', 'bachelor', 'master'],
    ageMin: 18,
    ageMax: 40,
    incomeLimit: null,
    isActive: true,
  },
  {
    slug: 'ignoaps-old-age-pension',
    title: 'Indira Gandhi National Old Age Pension Scheme',
    titleHi: 'इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन योजना',
    description: 'A non-contributory pension scheme that provides monthly financial assistance to elderly citizens living below the poverty line.',
    descriptionHi: 'एक गैर-अंशदायी पेंशन योजना जो गरीबी रेखा से नीचे रहने वाले बुजुर्ग नागरिकों को मासिक वित्तीय सहायता प्रदान करती है।',
    category: 'Social Welfare',
    categoryHi: 'समाज कल्याण',
    targetGroup: 'Senior Citizens',
    targetGroupHi: 'वरिष्ठ नागरिक',
    benefits: 'Monthly pension. Rs. 200/month for age 60-79 years, and Rs. 500/month for age 80 years and above.',
    benefitsHi: 'मासिक पेंशन। 60-79 वर्ष की आयु के लिए 200 रुपये/माह, और 80 वर्ष और उससे अधिक आयु के लिए 500 रुपये/माह।',
    eligibility: 'Age must be 60 years or above. Must belong to a Below Poverty Line (BPL) family.',
    eligibilityHi: 'आयु 60 वर्ष या उससे अधिक होनी चाहिए। गरीबी रेखा से नीचे (बीपीएल) परिवार से संबंधित होना चाहिए।',
    applicationProcess: 'Apply through the Gram Panchayat or corresponding urban local body.',
    applicationProcessHi: 'ग्राम पंचायत या संबंधित शहरी स्थानीय निकाय के माध्यम से आवेदन करें।',
    requiredDocuments: ['Age Proof', 'BPL Card', 'Bank Account Details', 'Aadhaar Card'],
    officialUrl: 'https://nsap.nic.in',
    ministry: 'Ministry of Rural Development',
    ministryHi: 'ग्रामीण विकास मंत्रालय',
    schemeType: 'Centrally Sponsored Scheme',
    occupationTags: [],
    stateTags: [],
    genderTags: [],
    educationTags: [],
    ageMin: 60,
    ageMax: null,
    incomeLimit: '100000',
    isActive: true,
  },
  // ================= SC Beneficiary Schemes =================
  {
    slug: 'nsfdc-term-loan',
    title: 'NSFDC Term Loan Scheme',
    titleHi: 'एनएसएफडीसी टर्म लोन योजना',
    description: 'Financial assistance for Scheduled Castes (SC) to start income-generating projects or businesses.',
    descriptionHi: 'आय-सृजन परियोजनाएं या व्यवसाय शुरू करने के लिए अनुसूचित जाति (एससी) को वित्तीय सहायता।',
    category: 'Business & Entrepreneurship',
    categoryHi: 'व्यापार और उद्यमिता',
    targetGroup: 'Scheduled Caste (SC) Beneficiaries',
    targetGroupHi: 'अनुसूचित जाति (एससी) लाभार्थी',
    benefits: 'Loans up to Rs. 30 lakhs for viable projects with very low interest rates.',
    benefitsHi: 'व्यवहार्य परियोजनाओं के लिए बहुत कम ब्याज दरों पर 30 लाख रुपये तक का ऋण।',
    eligibility: 'Must belong to SC category. Family income should not exceed Rs. 3,00,000 per annum.',
    eligibilityHi: 'एससी श्रेणी से संबंधित होना चाहिए। पारिवारिक आय 3,00,000 रुपये प्रति वर्ष से अधिक नहीं होनी चाहिए।',
    applicationProcess: 'Apply through State Channelizing Agencies (SCAs) of NSFDC.',
    applicationProcessHi: 'एनएसएफडीसी की राज्य चैनलाइजिंग एजेंसियों (एससीए) के माध्यम से आवेदन करें।',
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Aadhaar Card', 'Project Report', 'Bank Details'],
    officialUrl: 'https://nsfdc.nic.in',
    ministry: 'Ministry of Social Justice and Empowerment',
    ministryHi: 'सामाजिक न्याय और अधिकारिता मंत्रालय',
    schemeType: 'Central Sector Scheme',
    occupationTags: ['business', 'entrepreneur', 'self_employed'],
    stateTags: [],
    genderTags: [],
    educationTags: [],
    ageMin: 18,
    ageMax: 60,
    incomeLimit: '300000',
    isActive: true,
  },
  {
    slug: 'venture-capital-fund-sc',
    title: 'Venture Capital Fund for Scheduled Castes',
    titleHi: 'अनुसूचित जाति के लिए वेंचर कैपिटल फंड',
    description: 'Promotes entrepreneurship among Scheduled Castes by providing concessional finance to SC entrepreneurs.',
    descriptionHi: 'एससी उद्यमियों को रियायती वित्त प्रदान करके अनुसूचित जातियों के बीच उद्यमिता को बढ़ावा देता है।',
    category: 'Business & Entrepreneurship',
    categoryHi: 'व्यापार और उद्यमिता',
    targetGroup: 'SC Entrepreneurs',
    targetGroupHi: 'एससी उद्यमी',
    benefits: 'Financial assistance up to Rs. 15 crore per project for SC-led startups and companies.',
    benefitsHi: 'एससी के नेतृत्व वाले स्टार्टअप और कंपनियों के लिए प्रति परियोजना 15 करोड़ रुपये तक की वित्तीय सहायता।',
    eligibility: 'SC entrepreneurs/companies with at least 51% shareholding by SC entrepreneurs.',
    eligibilityHi: 'एससी उद्यमी/कंपनियां जिनमें एससी उद्यमियों की कम से कम 51% हिस्सेदारी है।',
    applicationProcess: 'Apply online through VCF-SC portal.',
    applicationProcessHi: 'वीसीएफ-एससी पोर्टल के माध्यम से ऑनलाइन आवेदन करें।',
    requiredDocuments: ['Caste Certificate', 'Company Registration', 'Business Plan', 'KYC Documents'],
    officialUrl: 'https://www.vcfsc.in',
    ministry: 'Ministry of Social Justice and Empowerment',
    ministryHi: 'सामाजिक न्याय और अधिकारिता मंत्रालय',
    schemeType: 'Central Sector Scheme',
    occupationTags: ['business', 'entrepreneur', 'self_employed'],
    stateTags: [],
    genderTags: [],
    educationTags: [],
    ageMin: 18,
    ageMax: null,
    incomeLimit: null,
    isActive: true,
  },
  {
    slug: 'stand-up-india',
    title: 'Stand-Up India Scheme',
    titleHi: 'स्टैंड-अप इंडिया योजना',
    description: 'Facilitates bank loans to at least one SC or ST borrower and at least one woman borrower per bank branch for setting up a greenfield enterprise.',
    descriptionHi: 'ग्रीनफील्ड उद्यम स्थापित करने के लिए प्रति बैंक शाखा कम से कम एक एससी/एसटी और एक महिला उधारकर्ता को बैंक ऋण की सुविधा।',
    category: 'Business & Entrepreneurship',
    categoryHi: 'व्यापार और उद्यमिता',
    targetGroup: 'SC/ST and Women Entrepreneurs',
    targetGroupHi: 'एससी/एसटी और महिला उद्यमी',
    benefits: 'Bank loans between 10 lakh and 1 Crore for setting up new enterprises.',
    benefitsHi: 'नए उद्यम स्थापित करने के लिए 10 लाख और 1 करोड़ रुपये के बीच का बैंक ऋण।',
    eligibility: 'SC/ST and/or woman entrepreneurs, above 18 years of age. Must not be in default to any bank.',
    eligibilityHi: 'एससी/एसटी और/या महिला उद्यमी, जिनकी आयु 18 वर्ष से अधिक हो।',
    applicationProcess: 'Apply through the Stand-Up India portal, directly at the branch, or via Lead District Manager (LDM).',
    applicationProcessHi: 'स्टैंड-अप इंडिया पोर्टल, शाखा में या एलडीएम के माध्यम से आवेदन करें।',
    requiredDocuments: ['Identity Proof', 'Caste Certificate', 'Project Report', 'Bank Details'],
    officialUrl: 'https://www.standupmitra.in',
    ministry: 'Ministry of Finance',
    ministryHi: 'वित्त मंत्रालय',
    schemeType: 'Central Sector Scheme',
    occupationTags: ['business', 'entrepreneur'],
    stateTags: [],
    genderTags: [], 
    educationTags: [],
    ageMin: 18,
    ageMax: null,
    incomeLimit: null,
    isActive: true,
  }
]

async function seed() {
  console.log('Seeding schemes...')
  try {
    for (const scheme of SEED_SCHEMES) {
      await db.insert(schemes)
        .values(scheme)
        .onConflictDoUpdate({
          target: schemes.slug,
          set: scheme,
        })
      console.log(`Upserted scheme: ${scheme.slug}`)
    }
    console.log('Seeding complete!')
  } catch (error) {
    console.error('Error seeding schemes:', error)
  } finally {
    await client.end()
  }
}

seed()
