'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { autoGenerateDossier } from '@/actions/dossiers';

interface GenerateSlipButtonProps {
  schemeId: string;
  defaultProjectCost: number;
  minMoratorium: number;
  disabled: boolean;
}

export function GenerateSlipButton({ schemeId, defaultProjectCost, minMoratorium, disabled }: GenerateSlipButtonProps) {
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const res = await autoGenerateDossier(schemeId, defaultProjectCost, minMoratorium);
      if (res.success && res.trackingCode) {
        router.push(`/dossiers/${res.trackingCode}`);
      } else {
        alert(res.error || 'Failed to auto-allot partner.');
      }
    } catch (err) {
      console.error(err);
      alert('An unexpected error occurred.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <button
      onClick={handleGenerate}
      disabled={disabled || loading}
      className={`flex-1 sm:flex-none px-6 py-3 rounded-full text-[14px] font-semibold transition-all duration-300 shadow-[0px_10px_30px_rgba(34,34,34,0.05)] h-[48px] flex items-center justify-center gap-2 ${
        disabled
          ? 'bg-foreground text-background opacity-50 cursor-not-allowed'
          : 'bg-primary text-primary-foreground hover:bg-primary/90 active:scale-95'
      }`}
    >
      {loading ? (
        <div className="w-5 h-5 border-2 border-current/30 border-t-current rounded-full animate-spin"></div>
      ) : (
        <>
          <span className="material-symbols-outlined text-[18px]">receipt_long</span>
          Generate Routing Slip
        </>
      )}
    </button>
  );
}
